- name: Revert virtual machines to original
  ansible.builtin.command:
    cmd: virsh snapshot-revert 'k8s-worker-{{ item }}' original
  become: true
  changed_when: true
  loop: "{{ localhost_workers }}"

- name: Wait for VMs to restart
  ansible.builtin.pause:
    seconds: 5
